import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
await mkdir('.test-results',{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
await page.locator('[data-testid="card-yasawi"]').waitFor();
await page.screenshot({path:'.test-results/desktop.png',fullPage:true});
console.log(JSON.stringify({title:await page.title(),cards:await page.locator('.landmark-card').count(),errors,bodyWidth:await page.evaluate(()=>document.body.scrollWidth)}));
await page.locator('[data-testid="card-yasawi"]').click();
await page.waitForTimeout(1200);
await page.screenshot({path:'.test-results/details.png',fullPage:true});
await page.locator('.detail-3d').click();
await page.locator('[data-model-loaded="yasawi"]').waitFor();
await page.screenshot({path:'.test-results/3d.png',fullPage:true});
await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});
await page.reload({waitUntil:'networkidle'});
await page.screenshot({path:'.test-results/mobile.png',fullPage:true});
await page.locator('[data-testid="card-yasawi"]').click();
await page.waitForTimeout(1000);
await page.screenshot({path:'.test-results/mobile-details.png',fullPage:true});
console.log(JSON.stringify({mobileWidth:await page.evaluate(()=>document.body.scrollWidth),errors}));
await browser.close();
