import { lazy, Suspense, useEffect, useMemo, useState, useRef } from 'react';
import { Box, Layers3, LocateFixed, Radar, Route, Navigation, Glasses, Search, SlidersHorizontal, List, X, ArrowUpRight, ArrowRight, MapPin, Landmark, Mountain, Building2, Columns3, Sparkles, Trophy, Check, ChevronDown, ExternalLink, BookOpen, Plus, Trash2, GripVertical, LoaderCircle, GraduationCap } from 'lucide-react';
import type { MuseumObject, Lang, Category, StudentProgress } from './types';
import { words, categories, categoryColors, distance } from './i18n';
import MuseumMap from './components/MuseumMap';
import Modal from './components/Modal';
import { Quiz, Progress } from './components/Learning';
import Guide from './components/Guide';
import { publicPath } from './publicPath';
const ModelViewer=lazy(()=>import('./components/ModelViewer'));
const catIcons={mausoleum:Landmark,archaeology:Columns3,architecture:Building2,nature:Mountain};
const allCategories=Object.keys(categories) as Category[];
function Photo({object,lang='kk',className=''}:{object:MuseumObject;lang?:Lang;className?:string}) {
  const [failed,setFailed]=useState(false);
  const Icon=catIcons[object.category];
  return failed?<div className={`photo-fallback ${className}`}><Icon size={48}/><span>QAZAQSTAN 3D</span></div>:<img className={className} src={object.imageGallery[0]||publicPath(`/previews/${object.id}.webp`)} alt={object.title[lang]} loading="lazy" onError={()=>setFailed(true)}/>;
}
function readProgress():StudentProgress {
  try{const raw=JSON.parse(localStorage.getItem('qazaqstan-3d-progress')||'{}');const result:StudentProgress={};for(const [id,value] of Object.entries(raw)){if(value&&typeof value==='object'&&'best' in value&&typeof value.best==='number'&&Number.isInteger(value.best)&&value.best>=0&&value.best<=5&&'completed' in value&&typeof value.completed==='boolean')result[id]={best:value.best,completed:value.completed}}return result;}catch{return {}}
}
export default function App() {
  const [lang,setLang]=useState<Lang>('kk'),[objects,setObjects]=useState<MuseumObject[]>([]),[loadError,setLoadError]=useState(false);
  const [selected,setSelected]=useState<MuseumObject|null>(null),[hovered,setHovered]=useState<string|null>(null),[query,setQuery]=useState('');
  const [category,setCategory]=useState<Category|'all'>('all'),[region,setRegion]=useState('all'),[era,setEra]=useState('all');
  const [enabledLayers,setEnabledLayers]=useState<Category[]>(allCategories),[only3D,setOnly3D]=useState(false),[onlyVR,setOnlyVR]=useState(false);
  const [catalogueOpen,setCatalogueOpen]=useState(true),[panel,setPanel]=useState<'layers'|'filters'|'route'|null>(null),[compass,setCompass]=useState(true);
  const [userLocation,setUserLocation]=useState<[number,number]|null>(null),[nearby,setNearby]=useState(false),[locating,setLocating]=useState(false),[resetKey,setResetKey]=useState(0);
  const [routeIds,setRouteIds]=useState<string[]>([]),[viewer,setViewer]=useState<{object:MuseumObject;vr:boolean}|null>(null),[quiz,setQuiz]=useState<MuseumObject|null>(null);
  const [progress,setProgress]=useState<StudentProgress>(readProgress),[progressOpen,setProgressOpen]=useState(false),[sourcesOpen,setSourcesOpen]=useState(false),[guideOpen,setGuideOpen]=useState(false),[toast,setToast]=useState('');
  const [detailTab,setDetailTab]=useState<'about'|'facts'|'sources'>('about');
  const toastTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const t=words[lang];
  useEffect(()=>{const abort=new AbortController();fetch(publicPath('/data/catalog.json'),{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{if(!Array.isArray(data)||data.length!==10)throw Error();setObjects(data.map(o=>({...o,modelUrl:publicPath(o.modelUrl),imageGallery:o.imageGallery.map(publicPath)})))}).catch(e=>{if(e.name!=='AbortError')setLoadError(true)});return()=>abort.abort()},[]);
  useEffect(()=>{document.documentElement.lang=lang;document.title=`QAZAQSTAN 3D · ${t.subtitle}`},[lang,t.subtitle]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(guideOpen)setGuideOpen(false);else if(panel)setPanel(null);else if(!viewer&&!quiz&&!progressOpen&&!sourcesOpen)setSelected(null)}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[guideOpen,panel,viewer,quiz,progressOpen,sourcesOpen]);
  useEffect(()=>()=>clearTimeout(toastTimer.current),[]);
  const notify=(text:string)=>{setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),5000)};
  const filtered=useMemo(()=>{
    const search=query.toLocaleLowerCase().trim();let result=objects.filter(o=>enabledLayers.includes(o.category)&&(category==='all'||category===o.category)&&(region==='all'||region===o.region.kk)&&(era==='all'||era===o.era)&&(!only3D||!!o.modelUrl)&&(!onlyVR||o.vrAvailable)&&(!search||[...Object.values(o.title),...Object.values(o.region),...Object.values(o.city),...Object.values(o.period),...Object.values(categories[o.category])].join(' ').toLocaleLowerCase().includes(search)));
    if(nearby&&userLocation)result=[...result].sort((a,b)=>distance(userLocation,a.coordinates)-distance(userLocation,b.coordinates));return result;
  },[objects,query,enabledLayers,category,region,era,only3D,onlyVR,nearby,userLocation]);
  useEffect(()=>{if(selected&&!filtered.some(o=>o.id===selected.id))setSelected(null)},[filtered,selected]);
  const route=useMemo(()=>routeIds.map(id=>objects.find(o=>o.id===id)!).filter(Boolean),[routeIds,objects]);
  const completed=objects.filter(o=>progress[o.id]?.completed).length;
  const select=(o:MuseumObject)=>{setSelected(o);setDetailTab('about');setPanel(null);if(window.innerWidth<768)setCatalogueOpen(false)};
  const resetFilters=()=>{setQuery('');setCategory('all');setRegion('all');setEra('all');setEnabledLayers(allCategories);setOnly3D(false);setOnlyVR(false);setNearby(false)};
  const locate=(sort=false)=>{
    if(!navigator.geolocation){notify(t.geoUnavailable);return}setLocating(true);
    navigator.geolocation.getCurrentPosition(p=>{setUserLocation([p.coords.latitude,p.coords.longitude]);setLocating(false);if(sort){setNearby(true);setCatalogueOpen(true);notify(t.nearbyOn)}},e=>{setLocating(false);notify(e.code===1?t.geoDenied:t.geoUnavailable)},{enableHighAccuracy:false,timeout:12000,maximumAge:60000});
  };
  const toggleRoute=(o:MuseumObject)=>{const exists=routeIds.includes(o.id);setRouteIds(ids=>exists?ids.filter(id=>id!==o.id):[...ids,o.id]);notify(exists?t.routeRemoved:t.routeAdded)};
  const completeQuiz=(id:string,score:number)=>{
    setProgress(p=>{const next={...p,[id]:{best:Math.max(p[id]?.best||0,score),completed:true}};try{localStorage.setItem('qazaqstan-3d-progress',JSON.stringify(next))}catch{notify(t.saveIssue)}return next});
  };
  const routeUrl=()=>{
    if(!route.length)return '#';const dest=route[route.length-1].coordinates.join(',');
    const params=new URLSearchParams({api:'1',destination:dest,travelmode:'driving'});
    if(route.length>1){params.set('origin',route[0].coordinates.join(','));if(route.length>2)params.set('waypoints',route.slice(1,-1).map(o=>o.coordinates.join(',')).join('|'))}
    return `https://www.google.com/maps/dir/?${params}`;
  };
  const showPanel=(value:typeof panel)=>setPanel(p=>p===value?null:value);
  const viewObject=selected||objects[0];
  const activeFilters=(category!=='all'?1:0)+(region!=='all'?1:0)+(era!=='all'?1:0)+(only3D?1:0)+(onlyVR?1:0);
  if(!objects.length)return <div className="loading-screen"><div className="logo-mark"><Box size={30}/></div><h1>QAZAQSTAN <span>3D</span></h1>{loadError?<><p>{t.error}</p><button className="button primary" onClick={()=>location.reload()}>{t.reload}</button></>:<><LoaderCircle className="spin" size={24}/><p>{t.loading}</p></>}</div>;
  return <div className="museum-app">
    <header className="topbar"><button className="brand" aria-label="QAZAQSTAN 3D" onClick={()=>{setSelected(null);setResetKey(k=>k+1);resetFilters()}}><span className="logo-mark"><Box size={29} strokeWidth={1.5}/></span><span><strong>QAZAQSTAN <em>3D</em></strong><small>{t.subtitle}</small></span></button>
      <nav className="main-nav" aria-label={t.mapTitle}>
        <button className={catalogueOpen?'active':''} onClick={()=>setCatalogueOpen(v=>!v)}><List size={17}/><span>{t.list}</span></button>
        <button className={panel==='layers'?'active':''} onClick={()=>showPanel('layers')}><Layers3 size={17}/><span>{t.layers}</span></button>
        <button onClick={()=>locate()} disabled={locating}>{locating?<LoaderCircle size={17} className="spin"/>:<LocateFixed size={17}/>}<span>{t.location}</span></button>
        <button className={nearby?'active':''} onClick={()=>{if(nearby)setNearby(false);else if(userLocation){setNearby(true);setCatalogueOpen(true)}else locate(true)}}><Radar size={17}/><span>{t.nearby}</span></button>
        <button className={panel==='route'?'active':''} onClick={()=>showPanel('route')}><Route size={17}/><span>{t.route}</span>{routeIds.length>0&&<i className="nav-count">{routeIds.length}</i>}</button>
        <button className={compass?'compass-toggle active':'compass-toggle'} onClick={()=>setCompass(v=>!v)}><Navigation size={17}/><span>{t.compass}</span></button>
      </nav><div className="header-actions"><button className="vr-header" onClick={()=>setViewer({object:viewObject,vr:true})}><Glasses size={19}/><span>{t.vr}</span></button><div className="language-switch" aria-label="Language">{(['kk','ru','en'] as Lang[]).map(l=><button key={l} lang={l} aria-pressed={lang===l} onClick={()=>setLang(l)} className={l===lang?'selected':''}>{l==='kk'?'ҚАЗ':l==='ru'?'РУС':'ENG'}</button>)}</div></div>
    </header>
    <div className="workspace">
      <main className={`main-area ${selected?'with-details':''}`}>
        <div className="search-toolbar"><div className="search-box"><Search size={19}/><input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" aria-label={t.clear} onClick={()=>setQuery('')}><X size={17}/></button>}<span className="search-kbd">⌕</span></div><button className={`filter-button ${panel==='filters'?'active':''}`} onClick={()=>showPanel('filters')}><SlidersHorizontal size={17}/><span>{t.filters}</span>{activeFilters>0&&<i>{activeFilters}</i>}</button></div>
        <MuseumMap objects={filtered} selected={selected} hovered={hovered} lang={lang} onSelect={select} userLocation={userLocation} route={route} locationRequest={()=>locate()} resetKey={resetKey} compass={compass} on3D={()=>setViewer({object:objects[0],vr:false})} catalogueOpen={catalogueOpen}/>
        {panel&&<section className={`floating-panel ${panel}-panel`}><header><h2>{panel==='layers'?t.layers:panel==='filters'?t.filters:t.routeTitle}</h2><button className="icon-button" aria-label={t.close} onClick={()=>setPanel(null)}><X size={18}/></button></header>
          {panel==='layers'&&<div className="layer-options"><label className="layer-row"><Layers3 size={19}/><span>{t.heritage}</span><input type="checkbox" checked={enabledLayers.includes('mausoleum')&&enabledLayers.includes('archaeology')} onChange={e=>setEnabledLayers(l=>e.target.checked?Array.from(new Set([...l,'mausoleum','archaeology'] as Category[])):l.filter(c=>c!=='mausoleum'&&c!=='archaeology'))}/></label>{allCategories.map(c=>{const Icon=catIcons[c];return <label className="layer-row" key={c}><Icon size={19} style={{color:categoryColors[c]}}/><span>{categories[c][lang]}</span><input type="checkbox" checked={enabledLayers.includes(c)} onChange={e=>setEnabledLayers(l=>e.target.checked?[...l,c]:l.filter(v=>v!==c))}/></label>})}<div className="panel-rule"/><label className="layer-row"><Box size={19}/><span>{t.available3d}</span><input type="checkbox" checked={only3D} onChange={e=>setOnly3D(e.target.checked)}/></label><label className="layer-row"><Glasses size={19}/><span>{t.availableVR}</span><input type="checkbox" checked={onlyVR} onChange={e=>setOnlyVR(e.target.checked)}/></label></div>}
          {panel==='filters'&&<div className="filter-fields"><label>{t.region}<select value={region} onChange={e=>setRegion(e.target.value)}><option value="all">{t.all}</option>{Array.from(new Set(objects.map(o=>o.region.kk))).map(r=><option key={r} value={r}>{objects.find(o=>o.region.kk===r)!.region[lang]}</option>)}</select></label><label>{t.period}<select value={era} onChange={e=>setEra(e.target.value)}><option value="all">{t.all}</option>{(['ancient','medieval','modern','natural'] as const).map(v=><option key={v} value={v}>{t[v]}</option>)}</select></label><label className="checkbox-line"><input type="checkbox" checked={only3D} onChange={e=>setOnly3D(e.target.checked)}/>{t.available3d}</label><label className="checkbox-line"><input type="checkbox" checked={onlyVR} onChange={e=>setOnlyVR(e.target.checked)}/>{t.availableVR}</label><button className="button secondary" onClick={resetFilters}>{t.clear}</button></div>}
          {panel==='route'&&<div className="route-content"><p>{t.routeHint}</p>{route.length===0?<div className="empty-route"><Route size={35}/><h3>{t.routeEmpty}</h3><button className="button primary" onClick={()=>{select(objects[0]);setPanel(null)}}>{t.explore}<ArrowRight size={16}/></button></div>:<><ol>{route.map((o,i)=><li key={o.id}><span>{i+1}</span><button onClick={()=>select(o)}>{o.title[lang]}</button><button className="icon-button" title={t.routeRemove} onClick={()=>toggleRoute(o)}><Trash2 size={15}/></button></li>)}</ol><p className="small-note">{t.routeApprox}</p><a className="button primary" href={routeUrl()} target="_blank" rel="noreferrer">{t.openRoute}<ExternalLink size={16}/></a><button className="text-button" onClick={()=>setRouteIds([])}>{t.clear}</button></>}</div>}
        </section>}
        {selected&&<section className="detail-panel" aria-label={selected.title[lang]}><button className="detail-close icon-button" onClick={()=>setSelected(null)} aria-label={t.close}><X size={20}/></button><div className="detail-visual"><Photo object={selected} lang={lang}/><div className="detail-image-shade"/><span className="detail-number">{String(objects.findIndex(o=>o.id===selected.id)+1).padStart(2,'0')} <small>/ 10</small></span><span className="image-label"><Box size={15}/>3D · 360°</span><button className="button detail-3d" onClick={()=>setViewer({object:selected,vr:false})}><Box size={19}/>{t.show3d}<ArrowUpRight size={18}/></button></div><div className="detail-content"><div className="detail-meta"><span style={{color:categoryColors[selected.category]}}>{categories[selected.category][lang]}</span><i/> {selected.period[lang]}</div><h2>{selected.title[lang]}</h2><div className="detail-location"><MapPin size={14}/>{selected.region[lang]}<span>{selected.coordinates.map(n=>n.toFixed(4)).join('°, ')}°</span></div><div className="detail-tabs">{(['about','facts','sources'] as const).map(tab=><button className={detailTab===tab?'active':''} key={tab} onClick={()=>setDetailTab(tab)}>{t[tab]}</button>)}</div><div className="detail-scroll">{detailTab==='about'?<><p>{selected.description[lang]}</p><h3>{t.significance}</h3><p>{selected.significance[lang]}</p></>:detailTab==='facts'?<ol className="facts-list">{selected.facts.map((f,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{f[lang]}</p></li>)}</ol>:<><SourceList object={selected} lang={lang}/><p className="small-note">{t.reconstruction}. {t.reconNote}</p></>}</div><div className="detail-actions"><button className="button primary" onClick={()=>setQuiz(selected)}><GraduationCap size={17}/>{t.quiz}</button><button className="button secondary" onClick={()=>toggleRoute(selected)} title={routeIds.includes(selected.id)?t.routeRemove:t.routeAdd}>{routeIds.includes(selected.id)?<Check size={17}/>:<Route size={17}/>}<span>{t.route}</span></button><button className="button secondary icon-action" onClick={()=>setViewer({object:selected,vr:true})} aria-label={t.vr}><Glasses size={18}/></button><a className="button secondary icon-action" title="Google Maps" href={`https://www.google.com/maps/search/?api=1&query=${selected.coordinates.join(',')}`} target="_blank" rel="noreferrer"><ExternalLink size={17}/></a></div></div></section>}
      </main>
      {catalogueOpen&&<aside className="catalogue"><div className="mobile-handle"/><div className="catalogue-header"><div className="catalogue-eyebrow"><span className="eyebrow">{t.landmarks.toUpperCase()}</span><span className="catalogue-count">10</span></div><h2>{t.collection}<span>.</span></h2><p>{t.catalogueSub}</p></div><div className="category-filters"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>{t.all}<span>{objects.length}</span></button>{allCategories.map(c=>{const Icon=catIcons[c];return <button className={category===c?'active':''} key={c} onClick={()=>setCategory(category===c?'all':c)}><Icon size={14}/>{categories[c][lang]}</button>})}</div><div className="catalogue-results"><span>{filtered.length} {t.places}</span><span><Box size={13}/> 3D <i/> <Glasses size={14}/> VR</span></div><div className="catalogue-list" data-testid="catalogue-list">{filtered.map((o,i)=>{const Icon=catIcons[o.category];return <button key={o.id} data-testid={`card-${o.id}`} className={`landmark-card ${selected?.id===o.id?'selected':''}`} onClick={()=>select(o)} onMouseEnter={()=>setHovered(o.id)} onMouseLeave={()=>setHovered(null)}><div className="card-photo"><Photo object={o} lang={lang}/><span className="photo-3d"><Box size={11}/> 3D</span></div><div className="card-content"><div className="card-category" style={{color:categoryColors[o.category]}}><Icon size={11}/>{categories[o.category][lang]}</div><h3>{o.title[lang]}</h3><p><MapPin size={11}/>{o.city[lang]||o.region[lang]}</p><span className="card-bottom"><span className="vr-badge"><Glasses size={11}/>VR</span>{progress[o.id]?.completed?<span className="test-complete"><Check size={11}/>{progress[o.id].best}/5</span>:<span>{o.period[lang]}</span>}{nearby&&userLocation&&<strong>{distance(userLocation,o.coordinates)} {t.distance}</strong>}</span></div><ArrowUpRight className="card-arrow" size={16}/></button>})}{!filtered.length&&<div className="no-results"><Search size={30}/><h3>{t.noResults}</h3><p>{t.noResultsHint}</p><button className="button secondary" onClick={resetFilters}>{t.clear}</button></div>}</div><div className="catalogue-footer"><button className="achievement-button" onClick={()=>setProgressOpen(true)}><span className="achievement-icon"><Trophy size={19}/></span><span><strong>{t.journey}</strong><small>{completed}/10 {t.tests}</small></span><span className="mini-progress" style={{background:`conic-gradient(#b58e49 ${completed*36}deg,#e6e9df 0)`}}><i>{completed}</i></span><ArrowRight size={16}/></button><div className="catalogue-bottom"><button onClick={()=>setSourcesOpen(true)}><BookOpen size={12}/>{t.sources}</button><span>© 2026</span></div></div></aside>}
    </div>
    <button className={`guide-launcher ${guideOpen?'is-open':''}`} onClick={()=>setGuideOpen(v=>!v)} aria-label={t.guideSubtitle}><span><Sparkles size={22}/></span><div><strong>{t.guide}</strong><small>{t.guideSubtitle}</small></div><span className="guide-online"/></button>
    {guideOpen&&<Guide object={viewObject} lang={lang} onClose={()=>setGuideOpen(false)}/>}
    {toast&&<div className="toast" role="status"><Check size={18}/>{toast}<button onClick={()=>setToast('')} aria-label={t.close}><X size={15}/></button></div>}
    {viewer&&<Suspense fallback={<div className="viewer-loading"><LoaderCircle className="spin" size={32}/>{t.loading}</div>}><ModelViewer object={viewer.object} lang={lang} onClose={()=>setViewer(null)} startVR={viewer.vr}/></Suspense>}
    {quiz&&<Quiz key={quiz.id} object={quiz} lang={lang} onClose={()=>setQuiz(null)} onComplete={completeQuiz}/>}
    {progressOpen&&<Progress objects={objects} progress={progress} lang={lang} onClose={()=>setProgressOpen(false)} onQuiz={o=>{setProgressOpen(false);setQuiz(o)}}/>}
    {sourcesOpen&&<Modal title={t.sources} closeLabel={t.close} onClose={()=>setSourcesOpen(false)} className="sources-modal"><p className="sources-intro">{t.modelSources} {t.reconNote}</p>{objects.map(o=><section className="source-object" key={o.id}><h3>{o.title[lang]}</h3><SourceList object={o} lang={lang}/></section>)}<p className="small-note">OpenStreetMap · © CARTO · Natural Earth (public domain)</p></Modal>}
  </div>
}

function SourceList({object,lang}:{object:MuseumObject;lang:Lang}) {
  const t=words[lang];
  return <div className="source-list">{object.sources.map((s,i)=><a key={i} href={s.url} target="_blank" rel="noreferrer"><BookOpen size={14}/><span>{s.title}</span><ExternalLink size={12}/></a>)}{object.coordinateSources.map((s,i)=><a key={`coord-${i}`} href={s.url} target="_blank" rel="noreferrer"><MapPin size={14}/><span>{s.title}</span><ExternalLink size={12}/></a>)}{object.imageCredits.map((c,i)=><div className="photo-credit" key={i}><strong>{t.photo}: {c.author}</strong><span>{c.license} · {t.accessed}: {c.accessed}</span><a href={c.url} target="_blank" rel="noreferrer">{t.original}<ExternalLink size={12}/></a></div>)}</div>
}
